version: '3'

services:
  # Microsoft SQL Server 2017 Linux (Developer Edition)
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: mssql2017dev
    environment:
      ACCEPT_EULA: Y
      # If you runs in production environment, you should change sa password.
      SA_PASSWORD: P@ssw0rd2017
      # If you have valid Product ID, set MSSQL_PID valiable.
      # See : https://hub.docker.com/_/microsoft-mssql-server
      #MSSQL_PID: Express
      # Against Garbled, set to Japanese environment.
      MSSQL_LCID: 1041
      MSSQL_COLLATION: Japanese_CI_AS
    volumes:
      - ./data/data:/var/opt/mssql/data
      - ./data/log:/var/opt/mssql/log
    ports:
      - 14330:1433
